name: Code Freeze
slug: code-freeze
type: meta
summary: Block merges during Code Freeze windows
subscribed_events:
  - pull_request.edited
  - pull_request.opened
  - pull_request.reopened
  - pull_request.synchronize
  - check_run.requested_action
  - check_run.rerequested
